"""food entries and symptom events

Revision ID: dcabfe49bcbb
Revises: 97427548649e
Create Date: 2026-09-04 16:28:58.138275

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dcabfe49bcbb'
down_revision = '97427548649e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.Column('food_name', sa.String(length=255), nullable=False),
    sa.Column('emoji', sa.String(length=32), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('portion', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('portion_unit', sa.String(length=20), nullable=True),
    sa.Column('serving_size', sa.String(length=20), nullable=True),
    sa.Column('preparation_method', sa.String(length=20), nullable=True),
    sa.Column('food_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('mood_after', sa.String(length=20), nullable=True),
    sa.Column('energy_level', sa.String(length=20), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("energy_level IS NULL OR energy_level IN ('low','normal','high')", name='ck_food_entries_energy_level'),
    sa.CheckConstraint("meal_type IN ('breakfast','lunch','dinner','snack','drink','supplement')", name='ck_food_entries_meal_type'),
    sa.CheckConstraint("mood_after IS NULL OR mood_after IN ('good','neutral','tired','uncomfortable','nauseous')", name='ck_food_entries_mood_after'),
    sa.CheckConstraint("portion_unit IS NULL OR portion_unit IN ('g','ml','cup','pcs','slice','bowl','pack')", name='ck_food_entries_portion_unit'),
    sa.CheckConstraint("preparation_method IS NULL OR preparation_method IN ('fried','boiled','steamed','grilled','raw','baked','roasted','other')", name='ck_food_entries_preparation_method'),
    sa.CheckConstraint("serving_size IS NULL OR serving_size IN ('small','medium','large','extra_large')", name='ck_food_entries_serving_size'),
    sa.CheckConstraint("source_type IS NULL OR source_type IN ('home_cooked','takeaway','dine_in','instant')", name='ck_food_entries_source_type'),
    sa.CheckConstraint('rating IS NULL OR rating BETWEEN 1 AND 5', name='ck_food_entries_rating'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('symptom_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('food_entry_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symptom', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("severity IS NULL OR severity IN ('mild','moderate','severe')", name='ck_symptom_events_severity'),
    sa.CheckConstraint("source IN ('entry_form','quick_check','manual')", name='ck_symptom_events_source'),
    sa.CheckConstraint("symptom IN ('heartburn','bloating','nausea','stomach_ache','gas','burping','regurgitation','difficulty_swallowing','chest_pain','vomit_blood','black_stool','other')", name='ck_symptom_events_symptom'),
    sa.ForeignKeyConstraint(['food_entry_id'], ['food_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('symptom_events')
    op.drop_table('food_entries')
    # ### end Alembic commands ###
